import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "New Next Js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        <NavBar></NavBar>

        <div>
          {children}
        </div>
        <footer className=" bg-slate-300 text-red-500 text-center">
          This is footer
        </footer>

      </body>
    </html>
  );
}
